### ISSUE TITLE
Add Campaign to player page

### ISSUE THREAD

**Issue by PABourdais** [GreepTheSheep/node-trackmania.io#50]
First of all, thank you very much for everything you have done with trackmania.io.

I have a small proposal, adding official campaign at least to player page. I don't know if with the data it'is possible to get all players ranking on each official campaign.

I would love to see the my profile with the rank on each official campaign (summer, spring, ..), and why not adding kind of an average ranking taking into account all official camapaign.

**Comment by GreepTheSheep** [comment]
Hello, Thank you for your suggestion! But unfortunately, it requires a higher level of access that I can't. Also, the Trackmania API does not give a specific player rank. Sorry
