### ISSUE TITLE
Allow API to give all COTDs played

### ISSUE THREAD

**Issue by NottCurious** [GreepTheSheep/node-trackmania.io#60]
Currently the module displays COTDs in pages of 25, maybe allow it to display all played ever.

**Comment by GreepTheSheep** [comment]
This was already set, you have to set the page on `player.cotd(page)`

If you want the first page you have to do `player.cotd(0)`
Like if you want the second page you have to do `player.cotd(1)`

you can do (on your project) a interaction button that loads the second page until the end, you already know that a page is 25 items and you have the total, so make a little algo that stop loading if you got the maximum
